# Generated by Django 4.1.7 on 2023-02-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='Название компании')),
                ('company_description', models.CharField(max_length=200, verbose_name='Описание компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id_home', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='default title', max_length=400, verbose_name='Адрес')),
                ('front_door', models.IntegerField(verbose_name='Количество парадных')),
                ('number_of_flats', models.IntegerField(verbose_name='Количество квартир в парадной')),
                ('bypass', models.BooleanField(verbose_name='Обход')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
    ]
