# Generated by Django 4.1.7 on 2023-02-21 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanag', '0002_company_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bupass',
            fields=[
                ('id_bupass', models.AutoField(primary_key=True, serialize=False)),
                ('door_open', models.BooleanField(verbose_name='Открыли дверь')),
                ('date', models.DateField(verbose_name='Дата обхода')),
                ('time', models.TimeField(verbose_name='Время обхода')),
                ('reaction', models.CharField(max_length=300, verbose_name='Реакция')),
            ],
            options={
                'verbose_name': 'Обход',
                'verbose_name_plural': 'Обходы',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id_form', models.AutoField(primary_key=True, serialize=False)),
                ('resp_name', models.CharField(max_length=70, verbose_name='Имя')),
                ('resp_phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Протокол обходов',
                'verbose_name_plural': 'Протоколы',
            },
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bupass_comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.bupass', verbose_name='Обход')),
                ('bupass_form_comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.survey', verbose_name='Форма обхода')),
                ('comp_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.company', verbose_name='Компания')),
                ('home_comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanag.home', verbose_name='Адрес')),
                ('user_comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
