# Generated by Django 4.1.7 on 2023-02-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanag', '0003_bupass_survey_companydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='comment',
            field=models.CharField(max_length=400, null=True, verbose_name='Комментарий'),
        ),
    ]
