# Generated by Django 4.2.1 on 2023-05-31 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanag', '0004_survey_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='bypass',
        ),
        migrations.RemoveField(
            model_name='home',
            name='front_door',
        ),
        migrations.RemoveField(
            model_name='home',
            name='number_of_flats',
        ),
    ]
