# Generated by Django 4.2.1 on 2023-05-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='id_company',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
